### ISSUE TITLE
Не импортируются модули

### ISSUE THREAD

**Issue by Artem3213212** [tarantool/cartridge-extensions#21]
Создаю lua модуль и пытаюсь его импортировать из другого:
![image](https://user-images.githubusercontent.com/37815717/145523152-3f2b56a3-af14-4ac4-85c4-5f1e22585d4a.png)
![image](https://user-images.githubusercontent.com/37815717/145523166-e75aec1d-9400-4ec7-b986-2b9b6417bcc7.png)
Если положить модуль в extentions тоже не работает.

**Comment by filonenko-mikhail** [comment]
Похоже что следует:
  - расположить модуль inspect.lua в директории extensions
  - загружать его с помощью require('extensions.inspect')
  
  
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/370551/156337174-4a8da30c-d9ae-44a5-8519-045b62c22c36.png">
